config/routes.rb
# 今後実装すること
# 新規登録時の実際のメールアドレスに確認メールを送る(deviseを使って実装可能)
# ユーザーIDの自動番号の変更（デフォルトで４桁など)

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  #ログイン状態であればノート一覧へ
  authenticated :user do
    root to: 'folders#index', as: :authenticated_root
  end

  #ログインしていない場合はホームページへ
  unauthenticated do
    root to: 'home#index'
  end

  # カスタムユーザーコントローラのルーティング
  resources :users, only: [:index, :destroy, :show]

  resources :folders do
    resources :memos
  end

  get 'learning_records', to: 'learning_records#show'
  resources :missions, only: [:index]

  # タグに関連するルート
  resources :tags, only: [:index, :create, :destroy]

  # お問い合わせルート
  resources :posts, only: [:new, :create, :index, :show]

  # 管理者ダッシュボード
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/daily_creation.rb
class DailyCreation < ApplicationRecord
  belongs_to :user
 
  def self.record_creation(user_id, date, memos_count, folders_count)
    daily_creation = find_or_initialize_by(user_id: user_id, date: date)
    daily_creation.memos_count += memos_count
    daily_creation.folders_count += folders_count
    daily_creation.save
  end
end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  has_many :memos, dependent: :destroy

    # 空白での保存を防ぐ
    validates :name, presence: true, length: { maximum: 10 }
    # 一人のユーザーが同じフォルダ名を2つ以上保存できないようにする
    validates :name, uniqueness: { scope: :user_id } 
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :folder, optional: true

  has_and_belongs_to_many :tags

  #最大文字数１０文字
  validates :title, length: { maximum: 10 }
end

app/models/mission.rb
class Mission < ApplicationRecord
  has_many :user_missions
  has_many :users, through: :user_missions
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 15 }
  validates :content, presence: true, length: { maximum: 200 }
  validates :read, inclusion: { in: [true, false] }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :memos

  # 空白での保存を防ぐ：最大文字数10
  validates :name, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # フォルダの関連づけ
  has_many :folders, dependent: :destroy

  # メモとの関連付け
  #dependent: :destroyでアカウント削除時に関連づいたメモも削除する
  has_many :memos, dependent: :destroy

  #お問合せ関連付け
  has_many :posts, dependent: :destroy

  #作成記録関連
  has_many :daily_creations, dependent: :destroy

  #ミッションとの関連付け
  has_many :user_missions, dependent: :destroy
  has_many :missions, through: :user_missions

  #文字数は２～８文字
  validates :username, presence: true, length: { minimum: 2, maximum: 8 }
  
  # パスワードに関するバリデーション
  validates :password, presence: true, length: { minimum: 8 }, on: :create
  validates :password, format: { 
    with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]{8,}+\z/,
    message: "は、最低8文字以上で、少なくとも1つの数字と大文字を含む必要があります" 
  }, on: :create


   # 新規登録時にデフォルトランクを設定
   before_create :set_default_rank
   # ポイントの変更後にランクを更新する
  after_save :update_rank_if_needed

  # ユーザーのミッション達成状況をチェックし、必要に応じてポイントを加算する
  def check_mission(memo_count_before_save)
    self.points ||= 0
  
    # 初めてのメモ作成時のミッションチェック
    message = check_and_complete_mission(1, 1) if memo_count_before_save == 1

    # メモ作成回数が3回に達した時のミッションチェック
    message ||= check_and_complete_mission(2, 3) if memo_count_before_save == 3

    # メモ作成回数が5回に達した時のミッションチェック
    message ||= check_and_complete_mission(3, 5) if memo_count_before_save == 5

    # メモ作成回数が10回に達した時のミッションチェック
    message ||= check_and_complete_mission(4, 10) if memo_count_before_save == 10

    # メモ作成回数が20回に達した時のミッションチェック
    message ||= check_and_complete_mission(5, 20) if memo_count_before_save == 20

    # メモ作成回数が30回に達した時のミッションチェック
    message ||= check_and_complete_mission(6, 30) if memo_count_before_save == 30

    # メモ作成回数が50回に達した時のミッションチェック
    message ||= check_and_complete_mission(7, 50) if memo_count_before_save == 50

    # メモ作成回数が77回に達した時のミッションチェック
    message ||= check_and_complete_mission(7, 77) if memo_count_before_save == 77

    # メモ作成回数が100回に達した時のミッションチェック
    message ||= check_and_complete_mission(7, 100) if memo_count_before_save == 100
  
    self.save if self.points_changed?
    message
  end

  private

    # 新規登録時にデフォルトランクを設定する
    def set_default_rank
      self.rank = '一般人' unless self.rank
    end

    # ポイントに応じてランクを更新する
    def update_rank_if_needed
      if self.points && self.points >= 3 && self.rank != '努力家'
        self.update(rank: '努力家')
      end
    end

    # 特定のミッションIDに対して、ユーザーが条件を満たしているかチェックし、
    # 条件を満たしていればミッションを達成としてポイントを加算し、UserMissionを更新する
    def check_and_complete_mission(mission_id, required_count)
      user_mission = self.user_missions.find_or_initialize_by(mission_id: mission_id)
      return nil if user_mission.completed
    
      mission = Mission.find_by(id: mission_id)
      return nil unless mission
    
      if self.memos.count == required_count
        self.points += mission.point_value
        user_mission.completed = true
        user_mission.save
    
        # ミッション達成時のみメッセージを返す
        "「#{mission.name}」を達成しました！"
      else
        # ミッション未達成の場合はnilを返す
        nil
      end
    end
end

app/models/user_mission.rb
class UserMission < ApplicationRecord
  belongs_to :user
  belongs_to :mission

  # デフォルト値の設定
  attribute :completed, :boolean, default: false
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  include AdminAccessControl

  def index
    @tags = Tag.all
    # Tag.newをしなければフォームからデータ保存ができない
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to tags_path, notice: '新しいタグを作成しました'
    else
      flash.now[:alert] = 'タグの作成に失敗しました'
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path, alert: 'タグを削除しました'
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_accounts.html.erb
<div class="popup" id="accounts-popup" style="display: none;">
  <p><%= current_user.username %> さんのNote</p>
  <p><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete } %></p>

  <%# 一般のユーザーのみに表示する %>
  <% if !current_user.admin? %>
    <p><%= link_to 'メモの記録をみる', learning_records_path %></p>
  <% end %>
</div>

app/views/shared/_contextMenu.html.erb
<div id="custom-context-menu" class="d-none">
  <%# フォルダ一覧のコンテキストメニュー %>
  <% if controller_name == 'folders' %>
    <%= link_to '#', data: { turbo_method: "delete", turbo_confirm: "本当に削除しますか？" },
                id: "delete-folder", class: 'dropdown-item' do %>
      <i class="fas fa-trash-alt"></i> 削除
    <% end %>

  <%# メモ一覧のコンテキストメニュー %>
  <% elsif controller_name == 'memos' %>
    <%= link_to '#', data: { turbo_method: "delete", turbo_confirm: "本当に削除しますか？" },
                id: "delete-memo", class: 'dropdown-item' do %>
      <i class="fas fa-trash-alt"></i> 削除
    <% end %>
  <% end %>
</div>

app/views/shared/_missionList.html.erb
<div class="missionList popup scrollable-table-container" id="mission-popup" style="display: none;">
  <h1>Missions</h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">ミッション名</th>
        <th scope="col">説明</th>
        <th scope="col">達成条件</th>
        <th scope="col">状態</th>
      </tr>
    </thead>
    <tbody>
      <% @missions.each do |mission| %>
        <tr>
          <td><%= mission.id %></td>
          <td><%= mission.name %></td>
          <td><%= mission.description %></td>
          <td><%= mission.completion_criteria %></td>
          <td class="<%= @completed_missions.include?(mission) ? 'text-success' : 'text-danger' %>">
            <%= @completed_missions.include?(mission) ? '達成済み' : '未達成' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_mypage.html.erb
<div class="popup" id="mypage-popup" style="display: none;">
  <div class="card mb-3">
    <div class="card-header">
      プロフィール
    </div>
    <div class="card-body">
      <h5 class="card-title">
        <p><%= current_user.username %></p>
        <p>現在のランク：<%= current_user.rank %></p>
        <p>現在のポイント:<%= current_user.points %></p> 
      </h5>
    </div>
  </div>

  <div class="card mb-3">
    <div class="card-header">
      アカウント情報
    </div>
    <div class="card-body">
      <h5 class="card-title">メールアドレス</h5>
      <p class="card-text"><%= current_user.email %></p>
      <div class="account-options">
        <p><%= link_to 'パスワードの変更', edit_user_registration_path %></p>
        <p><%= link_to "アカウント削除",
              registration_path(:user),
              data: { turbo_method: :delete, turbo_confirm: "削除してよろしいですか？" },
              style: "color: red;" %></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="col-md-2 d-none d-md-block bg-dark sidebar vh-100">
  <div class="position-sticky pt-3 h-100">   
    <!-- 現在のユーザー名を表示 -->
    <button id="accounts-link" class="btn text-white text-decoration-none"><%= current_user.username %>さんがログイン中</button>


    <!-- 一般ユーザー専用のナビゲーションバー -->
    <% unless current_user&.admin? %>
    
      <!-- ホーム画面へのリンク -->
      <%= link_to folders_path, class: 'nav-link text-white mb-3',style: 'margin-left: 17px;' do %>
        <i class="fas fa-home"></i> ホーム画面
      <% end %>

      <!-- マイページへのリンク -->
      <button id="mypage-link" class="nav-link text-white mb-3 text-decoration-none"style="margin-left: 17px;">
        <i class="fas fa-user"></i> マイページ
      </button>

      <!-- ノートがある場合に新規メモ作成へのリンクを表示 -->
      <% if @folder && @folder.persisted? %>
          <%= link_to new_folder_memo_path(@folder), class: 'nav-link text-white mb-3',style: 'margin-left: 17px;' do %>
            <i class="fas fa-pencil-alt"></i> 新規ページ
          <% end %>
      <% end %>
    

      <!-- メモの新規作成または編集ページでのみテンプレート選択リンクを表示 -->
      <% if controller_name == 'memos' && (action_name == 'new' || action_name == 'edit') %>
        <p><%= link_to '#', class: 'text-white',id: 'template-link', class: 'text-white', data: { bs_toggle: 'modal', bs_target: '#templateModal' },style: 'margin-left: 17px;' do %>
          <i class="fas fa-file-alt"></i> テンプレート
        <% end %></p>
      <% end %>

      <!-- ナビゲーションメニュー項目 -->
      <ul class="nav" style="border-top: 1px solid #ccc;">
        <!-- ドロップダウンの親要素 -->
        <li class="dropdown">
          <!-- ドロップダウントリガー -->
          <%= link_to 'ノート一覧', '#', class: 'nav-link dropdown-toggle', id: 'foldersDropdown', data: { bs_toggle: 'dropdown' }, aria: { expanded: 'false' }, style: 'color: white;' %>
          <!-- ドロップダウンメニュー -->
          <ul class="dropdown-menu bg-dark" aria-labelledby="foldersDropdown">
            <% @folders.each do |folder| %>
              <li>
                <%= link_to folder_memos_path(folder), class: 'dropdown-item', style: 'color: white;' do %>
                  <i class="fas fa-book"></i> <%= folder.name %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>

        <!-- ミッション一覧へのリンク -->
        <li class="nav-item">
          <button id="mission-link" class="nav-link text-decoration-none" style="color: white;"><i class="fas fa-clipboard"></i> ミッション一覧</button>
        </li>

        <!-- 管理者へのお問い合わせリンク -->
        <%= link_to new_post_path, class: 'nav-link text-white mb-3' do %>
          <i class="fas fa-envelope"></i> お問い合わせ
        <% end %>
      </ul>

    <% else %>

      <!-- 管理者専用のナビゲーションバー -->
      <ul class="nav" style="border-top: 1px solid #ccc;">
        <li class="nav-item">
          <%= link_to admin_dashboard_path, class: 'nav-link text-white' do %>
            <i class="fas fa-tools"></i> ダッシュボード
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to users_path, class: 'nav-link text-white' do %>
            <i class="fas fa-user-cog"></i> ユーザー管理
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to tags_path, class: 'nav-link text-white' do %>
            <i class="fas fa-tags"></i> タグ管理
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to posts_path, class: 'nav-link text-white' do %>
            <i class="fas fa-envelope"></i> お問合せ一覧
          <% end %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>