config/routes.rb
# 今後実装すること
# 新規登録時の実際のメールアドレスに確認メールを送る(deviseを使って実装可能)
# ユーザーIDの自動番号の変更（デフォルトで４桁など)

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  #ログイン状態であればノート一覧へ
  authenticated :user do
    root to: 'folders#index', as: :authenticated_root
  end

  #ログインしていない場合はホームページへ
  unauthenticated do
    root to: 'home#index'
  end

  # カスタムユーザーコントローラのルーティング
  resources :users, only: [:index, :destroy, :show]

  resources :folders do
    resources :memos
  end

  get 'learning_records', to: 'learning_records#show'
  resources :missions, only: [:index]

  # タグに関連するルート
  resources :tags, only: [:index, :create, :destroy]

  # お問い合わせルート
  resources :posts, only: [:new, :create, :index, :show]

  # 管理者ダッシュボード
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 15 }
  validates :content, presence: true, length: { maximum: 200 }
  validates :read, inclusion: { in: [true, false] }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include AdminAccessControl
  skip_before_action :check_admin, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "お問合せの送信が完了しました。"
      redirect_to new_post_path
    else
      render 'new'
    end
  end

  def index
    @posts = Post.all.order(id: :desc)
  end

  def show
    @post = Post.find_by(id: params[:id])
    @post.update(read: true)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :user_id, :read).merge(user_id: current_user.id)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="contact-back">
<h3> お問合せ管理</h3>
<hr>

<!-- お問い合わせ一覧テーブルコンテナ -->
<div class="post-admin-container mt-5"style="margin-left:20px;">
  <div class="table-responsive mx-auto" style="max-width: 75%; float: left;">
    <!-- お問い合わせ一覧テーブル -->
    <table class="table table-hover bordered-table sticky-header-table" style="table-layout: fixed;">
      <colgroup>
        <col style="width: 10%">
        <col style="width: 30%">
        <col style="width: 30%">
        <col style="width: 16%">
        <col style="width: 4%">
      </colgroup>

      <thead>
        <tr>
          <th scope="col" style="text-align: center;">ID</th>
          <th scope="col">タイトル</th>
          <th scope="col">送信日時</th>
          <th scope="col" style="padding-left: 0px;">確認</th>
          <th scope="col"></th>
        </tr>
      </thead>

      <tbody>

        <!-- 送られてきたお問合せ内容を表示 -->
        <% @posts.each do |post| %>
            <tr style="cursor: pointer;" onclick="window.location='<%= post_path(post) %>'">
            <th scope="row" style="text-align: center;"><%= post.id %></th>
              <td><%= post.title %></td>
              <td><%= post.created_at.strftime("%-m月%d日 %-H時%M分") %></td>
              <td><%= raw(post.read ? '<i class="fas fa-solid fa-check" style="color: #04be45;"></i>' : '') %></td>
              <td><i class="fas fa-angle-right fa-lg" style="color: #9fa0a3;"></i></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>

app/views/posts/new.html.erb
<div class="post-container">
  <div class="row justify-content-left">
    
      <h3 class="mb-3">お問合せの送信</h3>
      <hr>

      <!-- お問い合わせフォーム開始 -->
      <%= form_with model: @post, local: true, html: {class: 'needs-validation', novalidate: ''} do |form| %>
        <div class="mb-3">
          <%= form.label :title, '件名', class: 'form-label' %><span style="color: red; font-size: 0.8em;"> *</span>
          <%= form.text_field :title, class: 'form-control', style: 'width: 50%;', required: '', placeholder: '15文字以内で入力してください' %>


          <div class="invalid-feedback">
            件名を入力してください。
          </div>
          <p style="font-size: 0.8em; margin-left:20px;">お問合せの概要を記載してください。</p>
        </div>

        <div class="mb-3">
          <%= form.label :content, 'お問合せ内容', class: 'form-label' %><span style="color: red; font-size: 0.8em;"> *</span>
          <%= form.text_area :content, class: 'form-control form-control-textarea',style: 'width: 50%;', required: '', placeholder: '200文字以内で入力してください' %>
          <div class="invalid-feedback">
            お問い合わせ内容を入力してください。
          </div>
        </div>

        <%= form.submit "送信", class: 'btn btn-success btn-wide'%>
      <% end %>
      <!-- お問い合わせフォーム終了 -->
  </div>
</div>

app/views/posts/show.html.erb
<div class="contact-detail-back">
<div class="post-show-container mt-5" style="margin:0!important;">
    <a href="<%= posts_path %>" class="tag-a"><i class="fas fa-arrow-left"></i></a>
    <h3>詳細</h3>
</div>
<hr>
<div class="card">
  <div class="card-body">
    <p class="card-text text-muted">お問合せ番号: <%= @post.id %></p>
    <h5 class="card-title mb-4"><%= @post.title %></h5>
    <p class="card-text"><%= @post.content %></p>
    <% if @post.user %>
      <div class="mt-4">
        <p class="card-text text-muted">ユーザーID: <%= @post.user.id %></p>
        <p class="card-text text-muted">ユーザーのメールアドレス: <%= @post.user.email %></p>
      </div>
    <% else %>
      <p class="card-text text-muted">投稿者情報が見つかりません。</p>
    <% end %>
  </div>
</div>
</div>