config/routes.rb
# 今後実装すること
# 新規登録時の実際のメールアドレスに確認メールを送る(deviseを使って実装可能)
# ユーザーIDの自動番号の変更（デフォルトで４桁など)

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  #ログイン状態であればノート一覧へ
  authenticated :user do
    root to: 'folders#index', as: :authenticated_root
  end

  #ログインしていない場合はホームページへ
  unauthenticated do
    root to: 'home#index'
  end

  # カスタムユーザーコントローラのルーティング
  resources :users, only: [:index, :destroy, :show]

  resources :folders do
    resources :memos
  end

  get 'learning_records', to: 'learning_records#show'
  resources :missions, only: [:index]

  # タグに関連するルート
  resources :tags, only: [:index, :create, :destroy]

  # お問い合わせルート
  resources :posts, only: [:new, :create, :index, :show]

  # 管理者ダッシュボード
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :folder, optional: true

  has_and_belongs_to_many :tags

  #最大文字数１０文字
  validates :title, length: { maximum: 10 }
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  include NonAdminAccessControl
  before_action :set_folder
  before_action :set_memo, only: [:show, :edit, :update, :destroy]
  before_action :set_title_if_blank, only: [:update]
 
  def index
    if params[:tag_id].present?
      tag_id = params.require(:tag_id).to_i
      @memos = current_user.memos.joins(:tags).where(tags: { id: tag_id }).where(folder: @folder).distinct
    elsif params[:search].present?
      search_term = "%#{params.require(:search)}%"
      @memos = @folder.memos.where('title LIKE ?', search_term)
    else
      # すべてのメモを表示
      @memos = current_user.memos.where(folder: @folder)
    end
  end
 
  def show
    @memo = Memo.find(params[:id])
  end
 
  def new
    @memo = @folder.memos.build
  end
 
  def create
    @memo = @folder.memos.new(memo_params)
    @memo.user = current_user  # ログインしているユーザーをメモに関連付け

    # タイトルが空白時「無題」を入力
    @memo.title = '無題' if @memo.title.blank?
 
    if @memo.save
      # メモが保存されたら、DailyCreationモデルを使用して日別の作成数を更新
      DailyCreation.record_creation(current_user.id, Date.today, 1, 0)

      memo_count_before_save = current_user.memos.count
      mission_message = current_user.check_mission(memo_count_before_save)
 
      # フラッシュメッセージの設定
      flash[:notice] = 'メモが保存されました。' + mission_message.to_s
 
      redirect_to edit_folder_memo_path(@folder, @memo)
    else
      render :new, status: :unprocessable_entity
    end
  end
 
  def edit
    @memo = Memo.find(params[:id])
  end
 
  def update
    @memo = Memo.find(params[:id])

    # タイトルが空白時「無題」を入力
    params[:memo][:title] = '無題' if params[:memo][:title].blank?

    if @memo.update(memo_params)
      redirect_to edit_folder_memo_path(@folder, @memo), notice: 'メモが保存されました。'
    else
      render :edit
    end
  end
 
  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy
    redirect_to folder_memos_path(@folder), alert: 'メモが削除されました。'
  end
 
  private
 
  def set_folder
    @folder = Folder.find(params[:folder_id])
  end
 
  def set_memo
    @memo = @folder.memos.find(params[:id])
  end
 
  def memo_params
    params.require(:memo).permit(:title, :content, :tag_ids)
  end

  #空白の時に無題を入力
  def set_title_if_blank
    @memo.title = '無題' if @memo.title.blank?
  end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_form.html.erb
<div class="memos-back">
<%= form_with(model: [@folder, memo], local: true, class: 'needs-validation px-5', novalidate: true) do |form| %>
  
  <%# 現在アクセスしているノートとメモのタイトルを表示 %>
  <div class="mb-3" style="font-size: 18px;">
    <a href="<%= folder_memos_path(@folder) %>" class="tag-a"><i class="fas fa-arrow-left"></i></a> | 
    <%= @folder.name %>/<%= memo.title.present? ? memo.title : '新規メモ' %>
  </div>
<div>

  <!-- メモ入力フォーム -->
  <div class="row">
    <!-- タイトル入力フィールド -->
    <div class="col-md-8 mb-3">
      <%= form.text_field :title, class: 'form-control', placeholder: '無題', style: 'border: none; border-bottom: 0.5px solid grey; background: rgba(255, 255, 255, 0.8);margin-left:0px!important;' %>
    </div>

    <!-- タグ選択セレクトボックス -->
    <div class="col-md-2 mb-3">
      <%= form.collection_select :tag_ids, Tag.all, :id, :name, {include_blank: 'タグを選択...'}, class: 'form-select' %>
    </div>

    <div class="col-md-2 mb-3 d-flex align-items-end">
      <%= form.submit '保存', class: 'btn btn-primary' %>
    </div>
  </div>

  <!-- メモ本文入力テキストエリア -->
  <div class="mb-3">
    <%= form.text_area :content, id: 'memo_content', class: 'form-control custom-textarea',placeholder: '文字の入力、テンプレートを使用できます', style: 'height: 80vh; border: none; background: rgba(255, 255, 255, 0.8);margin-left:0px!important;' %>
  </div>
<% end %>


<%# テンプレートモーダル用 %>
<div class="modal fade" id="templateModal" tabindex="-1" aria-labelledby="templateModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="templateModalLabel">テンプレート選択</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <!-- テンプレート選択ボタン -->
      <div class="modal-body">
        <div class="d-flex justify-content-center mb-2">
          <%= button_tag '白紙にする', type: 'button', id: 'clear_textarea', class: 'btn btn-secondary w-100', data: { template_type: 'clear_textarea' } %>
        </div>
        <div class="d-flex justify-content-center mb-2">
          <%= button_tag 'プログラミング用テンプレート', type: 'button', id: 'insert_text2', class: 'btn btn-secondary w-100', data: { template_type: 'insert_text2' } %>
        </div>
        <div class="d-flex justify-content-center">
          <%= button_tag 'エラー用テンプレート', type: 'button', id: 'insert_text3', class: 'btn btn-secondary w-100', data: { template_type: 'insert_text3' } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/memos/edit.html.erb
<!-- メモ入力フォームのレンダリング -->
<%= render 'form', memo: @memo %>

app/views/memos/index.html.erb
<div class="folders-back">

  <!-- 右クリック削除用のメニュー -->
  <%= render 'shared/contextMenu' %>

  <!-- メモ一覧 -->
  <div class="col-md-12">
  <!-- 現在のアクセス中のノート名表示 -->
    <h3 class="note-name"><%= @folder.name %></h3>
    <hr>

    <!-- 検索フォーム -->
    <div class="d-flex justify-content-between mb-3">
      <%= form_with(url: folder_memos_path(@folder), method: :get, local: true, class: "d-flex flex-grow-1 me-2") do |form| %>
        <%= form.label :search, "メモ検索", class: "visually-hidden" %>
        <%= form.text_field :search, class: "form-control me-2", placeholder: "タイトルで検索", style: "max-width: 200px;" %> <!-- 幅をカスタムで調整 -->
        <%= form.submit "検索", class: "btn btn-outline-secondary custom-button" %>
      <% end %>

      <!-- タグ検索フォーム -->
      <%= form_with(url: folder_memos_path(@folder), method: :get, local: true, class: "d-flex") do |form| %>
        <%= form.label :tag_id, "タグで検索", class: "visually-hidden" %>
        <%= form.collection_select :tag_id, Tag.all, :id, :name, { prompt: 'タグで選択' }, { class: "form-select me-2" } %>
        <%= form.submit "検索", class: "btn btn-outline-secondary custom-button" %>
      <% end %>
    </div>

    <!-- メモ一覧 -->
    <div class="row"  style="min-height: 70vh; display: flex;">
      <!-- メモが存在しない場合のメッセージ -->
      <% if @memos.empty? %>
        <div class="default-memo-ex col-md-5"style="margin-left: 10px;">
          <i class="fas fa-pencil-alt fa-4x m-3"></i>
          <p>最初のメモを作成する</p>
          <p style="color: #777;">開始するには、サイドバーの「<%= link_to '新規ページ', new_folder_memo_path(@folder)%>」をクリックします。</p>
        </div>
      <% else %>
        <div class="col-md-5" style="overflow-y: auto; max-height: 70vh;">
          <%= turbo_frame_tag 'memo_list' do %>
            <div class="folder-group" data-folder-id="<%= @folder.id %>">
              <% @memos.each do |memo| %>
                <!-- メモ一覧の各項目 -->
                <div class="folder-group-item list-group-item d-flex justify-content-between align-items-center border-bottom" style="padding: 1rem; border-color: black !important; background-color: rgba(255, 255, 255, 0.5);margin-left:20px;" data-memo-id="<%= memo.id %>">

                  <div style="font-size: 1rem;">
                    <!-- クリック時にメモ詳細を表示 -->
                    <%= link_to memo.title, folder_memo_path(@folder, memo), data: { turbo_frame: 'memo_detail' }, class: 'text-dark text-decoration-none' %>
                  </div>
                  <div class="edit-button" style="font-size: 0.75rem;">
                    <!-- data: { turbo_frame: '_top' }で全ての変更 -->
                    <%= link_to edit_folder_memo_path(@folder, memo), data: { turbo_frame: '_top' } do %>
                    <i class="fas fa-edit "style="font-size: 1em;"> 編集</i> 
                    <% end %>
                  </div>

                  <!-- メモに関連付けられたタグの表示 -->
                  <div>
                    <% memo.tags.each do |tag| %>
                      <span class="badge bg-secondary" style="font-size: 0.75rem;"><%= tag.name %></span>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>


        <!-- メモ詳細 (show.html.erb)を表示-->
        <div class="col-md-7">
          <%= turbo_frame_tag 'memo_detail' do %><% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/memos/new.html.erb
<!-- メモ入力フォームのレンダリング -->
<%= render 'form', memo: @memo %>

app/views/memos/show.html.erb
<%= turbo_frame_tag 'memo_detail' do %>
  <!-- メモ内容部分 -->
  <div class="memo-content">
    <div class="border p-3 overflow-auto" style="height: 250px; white-space: pre-wrap; box-shadow: 0 0 3px rgba(0, 0, 0, 0.1);">
      <p class="mb-4"><%= @memo.content %></p>
    </div>
  </div>

  <!-- タイトルと情報 -->
  <div class="memo-detail">
    <h4 class="mt-4"><%= @memo.title %></h4>

    <!-- 情報 -->
    <div class="mt-3" style="font-size: 0.75rem;">
      <p>作成日: <%= @memo.created_at.strftime("%Y年%m月%d日 %H:%M") %></p>
      <p>更新日: <%= @memo.updated_at.strftime("%Y年%m月%d日 %H:%M") %></p>
    </div>
  </div>
<% end %>